language: cpp

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686
 - touch Makefile.depend

script:
 - make
